// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
// import 'firebase_options.dart';
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp5J_2R6PV-pKodW4GaSb3KfD0TjmTYj0',
    appId: '1:343243779678:web:ea7f2ca63ef17985da4ecf',
    messagingSenderId: '343243779678',
    projectId: 'blog-app-92b33',
    authDomain: 'blog-app-92b33.firebaseapp.com',
    storageBucket: 'blog-app-92b33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BjlIItn0dnhTBNlqwho7WYh33py35I0',
    appId: '1:343243779678:android:cc32d8df8be75f31da4ecf',
    messagingSenderId: '343243779678',
    projectId: 'blog-app-92b33',
    storageBucket: 'blog-app-92b33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUIh1YictovnT90CWobp-20OYI0VNqPak',
    appId: '1:343243779678:ios:93f8a4b600a6d1a0da4ecf',
    messagingSenderId: '343243779678',
    projectId: 'blog-app-92b33',
    storageBucket: 'blog-app-92b33.appspot.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUIh1YictovnT90CWobp-20OYI0VNqPak',
    appId: '1:343243779678:ios:93f8a4b600a6d1a0da4ecf',
    messagingSenderId: '343243779678',
    projectId: 'blog-app-92b33',
    storageBucket: 'blog-app-92b33.appspot.com',
    iosBundleId: 'com.example.blogapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp5J_2R6PV-pKodW4GaSb3KfD0TjmTYj0',
    appId: '1:343243779678:web:635496990c6369e4da4ecf',
    messagingSenderId: '343243779678',
    projectId: 'blog-app-92b33',
    authDomain: 'blog-app-92b33.firebaseapp.com',
    storageBucket: 'blog-app-92b33.appspot.com',
  );

}